### Update dashboard definition being used
PUT http://localhost:8080/dashboard/definition
Content-Type: application/json

{
	"context": {
		"timeZone": "Europe/Berlin",
		"locale": "de_DE"
	},
	"display": {
		"width": 1000,
		"height": 500,
		"columnCount": 10,
		"rowCount": 5
	},
	"widgets": [
        {
			"widgetType": "weather",
			"display": {
				"startColumn": 1,
				"columnSpan": 10,
				"startRow": 4,
				"rowSpan": 2,
				"align": "center",
				"justify": "center"
			},
			"lat": 50.91,
			"lon": 11.56
		},
		{
			"widgetType": "googlecalendar",
			"display": {
				"startColumn": 6,
				"columnSpan": 5,
				"startRow": 1,
				"rowSpan": 3
			},
            "serviceAccount": {
                "project_id": "{{googlecalendar.serviceAccount.project_id}}",
                "private_key_id": "{{googlecalendar.serviceAccount.private_key_id}}",
                "private_key": "{{googlecalendar.serviceAccount.private_key}}",
                "client_email": "{{googlecalendar.serviceAccount.client_email}}",
                "client_id": "{{googlecalendar.serviceAccount.client_id}}",
                "token_uri": "{{googlecalendar.serviceAccount.token_uri}}",
                "universe_domain": "{{googlecalendar.serviceAccount.universe_domain}}"
            },
			"calendarId": "{{googlecalendar.calendarId}}"
		},
		{
			"widgetType": "jenah",
			"display": {
				"startColumn": 1,
				"columnSpan": 5,
				"startRow": 1,
				"rowSpan": 3
			},
			"apiClient": "{{jenah.apiClient}}",
			"apiAuthorization": "{{jenah.apiAuthorization}}",
			"station": "Zeiss-Werk"
		}
	]
}

### Show dashboard
GET http://localhost:8080/dashboard
